# -*- coding: utf-8 -*-
"""Tratar Dados 001.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12h0AUF1Dn7PEqYUDwaz8OjYdIQ4Nu3mU
"""

#Importando o pacote pandas
import pandas as pd

# Carregando os dados e armazenando em um Dataframe
df_notas = pd.read_excel('notas.xlsx')

# Visualizando o Dataframe
df_notas

# Renomeia as variaves
df_notas.rename(columns = {'ID':'ID_ALUNO', 'DISCIPLINA':'MATÉRIA', 'NT':'NOTAS'}, inplace = True)

df_notas

# Vamos descartar os valores duplicados
df_notas.drop_duplicates(['ID_ALUNO', 'MATÉRIA', 'NOTAS'], inplace=True)

df_notas

# Visualiando a mediana dos dados
df_notas['NOTAS'].median()

# Preenchendo os valores NaN com a mediana dos dados
df_notas['NOTAS'] = df_notas['NOTAS'].fillna((df_notas['NOTAS'].median()))

df_notas

# Visualiando a média dos dados
df_notas['NOTAS'].mean()

# Preenchendo valores nulos com a média
df_notas = pd.read_excel('notas.xlsx')
df_notas.rename(columns = {'ID':'ID_ALUNO', 'DISCIPLINA':'MATÉRIA', 'NT':'NOTAS'}, inplace = True)
df_notas.drop_duplicates(['ID_ALUNO', 'MATÉRIA', 'NOTAS'], inplace=True)
df_notas

# Preenchendo os valores NaN com a media dos dados
df_notas['NOTAS'] = df_notas['NOTAS'].fillna((df_notas['NOTAS'].mean()))
df_notas

# Preenchendo valores nulos com zero
# Carregando o arquivo
df_notas = pd.read_excel('notas.xlsx')
df_notas.rename(columns = {'ID':'ID_ALUNO', 'DISCIPLINA':'MATÉRIA', 'NT':'NOTAS'}, inplace = True)
df_notas.drop_duplicates(['ID_ALUNO', 'MATÉRIA', 'NOTAS'], inplace=True)
df_notas

# Preenchendo valors com zero
df_notas['NOTAS'] = df_notas['NOTAS'].fillna(0)
df_notas

